plugins:
  - prettier-plugin-go-template

tabWidth: 4
endOfLine: lf
singleQuote: true
printWidth: 100000
trailingComma: none
bracketSameLine: true
quoteProps: consistent
experimentalTernaries: true

overrides:
  - files: ["*.md"]
    options:
      tabWidth: 2
      singleQuote: false

  - files: ["*.json", "*.yaml", "*.yml"]
    options:
      tabWidth: 2
      singleQuote: false

  - files: ["*.scss"]
    options:
      singleQuote: false

  - files:
      - "layouts/**/*.html"
      - "themes/**/layouts/**/*.html"
    options:
      parser: go-template
